Web/FootballPredictor.Web/Controllers/StandingsController.cs
namespace FootballPredictor.Web.Controllers
{
    using FootballPredictor.Services.Data;
    using FootballPredictor.Web.ViewModels.Standings;
    using Microsoft.AspNetCore.Mvc;

    public class StandingsController : BaseController
    {
        private readonly IStandingsService standingsService;
        private readonly ITeamsService teamsService;

        public StandingsController(IStandingsService standingsService, ITeamsService teamsService)
        {
            this.standingsService = standingsService;
            this.teamsService = teamsService;
        }

        public IActionResult Leagues()
        {
             return this.View();
        }

        public IActionResult EnglishPremierLeague()
        {
            var leagueName = "English Premier League";
            var model = this.standingsService.LeagueStandings(leagueName);

            return this.View("LeagueStandings", model);
        }

        public IActionResult GermanBundesliga()
        {
            var leagueName = "German 1. Bundesliga";
            var model = this.standingsService.LeagueStandings(leagueName);

            return this.View("LeagueStandings", model);
        }

        public IActionResult ItalianSerieA()
        {
            var leagueName = "Italian Serie A";
            var model = this.standingsService.LeagueStandings(leagueName);

            return this.View("LeagueStandings", model);
        }

        public IActionResult SpainPrimeraDivision()
        {
            var leagueName = "Spain Primera Division";
            var model = this.standingsService.LeagueStandings(leagueName);

            return this.View("LeagueStandings", model);
        }
    }
}

Web/FootballPredictor.Web/Controllers/TeamsController.cs
namespace FootballPredictor.Web.Controllers
{
    using FootballPredictor.Services.Data;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class TeamsController : BaseController
    {
        private readonly ITeamsService teamsService;

        public TeamsController(ITeamsService teamsService)
        {
            this.teamsService = teamsService;
        }

        [Authorize]
        public IActionResult Squad(int id)
        {
            var model = this.teamsService.GetSquad(id);

            return this.View(model);
        }

        [Authorize]
        public IActionResult Team(int id)
        {
            var model = this.teamsService.TeamDetails(id);

            return this.View("TeamDetails", model);
        }
    }
}

Web/FootballPredictor.Web/Views/Standings/LeagueStandings.cshtml
@model FootballPredictor.Web.ViewModels.Standings.LeagueViewModel
@{
    this.ViewData["Title"] = "League Standing";
}
<h1>@Model.Name</h1>

<div>
    <style>
        table {
            counter-reset: rowNumber;
        }

            table tr > td:first-child {
                counter-increment: rowNumber;
            }

            table tr td:first-child::before {
                content: counter(rowNumber);
                min-width: 1em;
                margin-right: 0.5em;
            }
    </style>
</div>
<div>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th scope="col" class="whiteColor">Rank</th>
                <th scope="col" class="whiteColor">Team</th>
                <th scope="col" class="whiteColor">Played Matches</th>
                <th scope="col" class="whiteColor">Wins</th>
                <th scope="col" class="whiteColor">Draws</th>
                <th scope="col" class="whiteColor">Looses</th>
                <th scope="col" class="whiteColor">Scored Goals</th>
                <th scope="col" class="whiteColor">Conceded Goals</th>
                <th scope="col" class="whiteColor">Points</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var team in this.Model.Teams)
            {

                <tr class="table-light">
                    <td></td>
                    <th scope="row"><a asp-controller="Teams" asp-action="Team" asp-route-id="@team.Id">@team.Name</a></th>
                    <td>@team.MatchesPlayed</td>
                    <td>@team.Wins</td>
                    <td>@team.Draws</td>
                    <td>@team.Looses</td>
                    <td>@team.ScoredGoals</td>
                    <td>@team.ConcededGoals</td>
                    <td>@team.Points</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Web/FootballPredictor.Web/Views/Standings/Leagues.cshtml
@{
    this.ViewData["Title"] = "Results";
}
<h1>Pick a League</h1>
<a class="btn btn-block btn-danger text-white mb-3" href="/Standings/EnglishPremierLeague">English Premier League</a>
<a class="btn btn-block btn-success text-white mb-3" href="/Standings/GermanBundesliga">German 1. Bundesliga</a>
<a class="btn btn-block btn-dark text-white mb-3" href="/Standings/SpainPrimeraDivision">Spain Primera Division</a>
<a class="btn btn-block btn-primary text-white mb-3" href="/Standings/ItalianSerieA">Italian Serie A</a>
<br />
<br />
<br />
<br />
<br />
<a class="btn btn-block btn-warning text-light mb-3" href="/Players/Rankings">Top Scorers All Leagues</a>