Web/FootballPredictor.Web/Controllers/MatchesController.cs
namespace FootballPredictor.Web.Controllers
{
    using System.Security.Claims;

    using FootballPredictor.Common;
    using FootballPredictor.Services.Data;
    using FootballPredictor.Web.ViewModels.Matches;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class MatchesController : BaseController
    {
        private readonly IMatchesService matchesService;
        private readonly IUsersService usersService;
        private readonly IPredictionsService predictionsService;

        public MatchesController(IMatchesService matchesService, IUsersService usersService, IPredictionsService predictionsService)
        {
            this.matchesService = matchesService;
            this.usersService = usersService;
            this.predictionsService = predictionsService;
        }

        public IActionResult Fixtures(int id = 1)
        {
            if (this.User.Identity.IsAuthenticated)
            {
                var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

                var gameweek = GlobalConstants.CurrentWeek + id - 1;
                var viewModel = new ListOfLeaguesViewModel
                {
                    PageNumber = id,
                    Gameweek = gameweek,
                    Leagues = this.matchesService.GetAll(userId, gameweek),
                    ThisUserPredictionsCount = this.predictionsService.PredictionsByUserCount(userId),
                };

                return this.View(viewModel);
            }
            else
            {
                var gameweek = GlobalConstants.CurrentWeek + id - 1;
                var viewModel = new ListOfLeaguesViewModel
                {
                    PageNumber = id,
                    Gameweek = gameweek,
                    Leagues = this.matchesService.GetAll(gameweek),
                };

                return this.View(viewModel);
            }
        }

        public IActionResult Results(int id = 1)
        {
            var gameweek = GlobalConstants.CurrentWeek - id;
            var viewModel = new ListOfResultsViewModel
            {
                PageNumber = id,
                Gameweek = gameweek,
                Leagues = this.matchesService.GetAll(gameweek),
            };

            return this.View(viewModel);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public IActionResult Simulate()
        {
            this.matchesService.Simulate();

            return this.Redirect("/Matches/Fixtures");
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public IActionResult UserPoints()
        {
            this.usersService.AddPointsToUser();

            return this.Redirect("/");
        }
    }
}

Web/FootballPredictor.Web/Controllers/MiniLiguesController.cs
namespace FootballPredictor.Web.Controllers
{
    using System.Security.Claims;
    using System.Threading.Tasks;

    using FootballPredictor.Services.Data;
    using FootballPredictor.Web.ViewModels.MiniLigues;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class MiniLiguesController : BaseController
    {
        private readonly IMiniLiguesService miniLiguesService;

        public MiniLiguesController(IMiniLiguesService miniLiguesService)
        {
            this.miniLiguesService = miniLiguesService;
        }

        [Authorize]
        public IActionResult All()
        {
            var model = this.miniLiguesService.All();

            return this.View(model);
        }

        [Authorize]
        public IActionResult Create()
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var creatorAlready = this.miniLiguesService.IsACreator(userId);

            if (creatorAlready)
            {
                this.TempData["Message"] = "You can make only one Mini League for now.";
                return this.Redirect("/MiniLigues/MyMiniLigues");
            }

            return this.View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreateInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            if (model.Password != model.ConfirmPassword)
            {
                this.TempData["Message"] = "Your Confirm Password was differrent from your Password!";
                return this.View();
            }

            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            await this.miniLiguesService.CreateAsync(model, userId);

            return this.Redirect("/MiniLigues/Dashboard");
        }

        [Authorize]
        public IActionResult Dashboard(string id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var member = this.miniLiguesService.IsAMember(id, userId);

            if (!member)
            {
                return this.Redirect("/MiniLigues/All");
            }

            var model = this.miniLiguesService.Dashboard(id);

            return this.View(model);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Remove(string id)
        {
            var creatorId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            await this.miniLiguesService.RemoveAsync(id, creatorId);

            return this.Redirect("/MiniLigues/MyMiniLigues");
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Leave(string id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            await this.miniLiguesService.RemoveAsync(userId, id);
            return this.Redirect("/MiniLigues/MyMiniLigues");
        }

        [Authorize]
        public IActionResult Join(string id)
        {
            var miniLigueName = this.miniLiguesService.MiniLigueName(id);
            var model = new JoinViewModel
            {
                Id = id,
                Name = miniLigueName,
            };

            return this.View(model);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Join(JoinViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            if (this.miniLiguesService.IsAMember(model.Id, userId))
            {
                var miniLigueName = this.miniLiguesService.MiniLigueName(model.Id);
                model.Name = miniLigueName;
                this.TempData["Message"] = "You are already a member of this League!";
                return this.View(model);
            }
            else if (!this.miniLiguesService.IsCorrectPassword(model.Id, model.Password))
            {
                var miniLigueName = this.miniLiguesService.MiniLigueName(model.Id);
                model.Name = miniLigueName;
                this.TempData["Message"] = "Invalid Password!";
                return this.View(model);
            }

            await this.miniLiguesService.Join(model, userId);

            return this.Redirect("/MiniLigues/MyMiniLigues");
        }

        [Authorize]
        public IActionResult MyMiniLigues()
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var model = this.miniLiguesService.MiniLiguesByUser(userId);

            return this.View(model);
        }
    }
}

Web/FootballPredictor.Web/Controllers/StandingsController.cs
namespace FootballPredictor.Web.Controllers
{
    using FootballPredictor.Services.Data;
    using FootballPredictor.Web.ViewModels.Standings;
    using Microsoft.AspNetCore.Mvc;

    public class StandingsController : BaseController
    {
        private readonly IStandingsService standingsService;
        private readonly ITeamsService teamsService;

        public StandingsController(IStandingsService standingsService, ITeamsService teamsService)
        {
            this.standingsService = standingsService;
            this.teamsService = teamsService;
        }

        public IActionResult Leagues()
        {
             return this.View();
        }

        public IActionResult EnglishPremierLeague()
        {
            var leagueName = "English Premier League";
            var model = this.standingsService.LeagueStandings(leagueName);

            return this.View("LeagueStandings", model);
        }

        public IActionResult GermanBundesliga()
        {
            var leagueName = "German 1. Bundesliga";
            var model = this.standingsService.LeagueStandings(leagueName);

            return this.View("LeagueStandings", model);
        }

        public IActionResult ItalianSerieA()
        {
            var leagueName = "Italian Serie A";
            var model = this.standingsService.LeagueStandings(leagueName);

            return this.View("LeagueStandings", model);
        }

        public IActionResult SpainPrimeraDivision()
        {
            var leagueName = "Spain Primera Division";
            var model = this.standingsService.LeagueStandings(leagueName);

            return this.View("LeagueStandings", model);
        }
    }
}

Web/FootballPredictor.Web/Controllers/UsersController.cs
namespace FootballPredictor.Web.Controllers
{
    using FootballPredictor.Services.Data;
    using FootballPredictor.Web.ViewModels.Users;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class UsersController : BaseController
    {
        private readonly IUsersService usersService;

        public UsersController(IUsersService usersService)
        {
            this.usersService = usersService;
        }

        public IActionResult Rankings()
        {
            var model = new EnumRankingsViewModel
            {
                Rankings = this.usersService.Rankings(),
            };

            return this.View(model);
        }

        [Authorize]
        public IActionResult PointsByUser(string id)
        {
            var model = this.usersService.UserGameweeksPoints(id);
            return this.View(model);
        }
    }
}

Web/FootballPredictor.Web/Views/Shared/_Layout.cshtml
@using FootballPredictor.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
</head>
<body>
    <header>
        <nav id="navbar" class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Standings" asp-action="Leagues">Standings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Matches" asp-action="Results">Results</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Matches" asp-action="Fixtures">Fixtures</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Predictions" asp-action="All">Predictions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Rankings">Users Ranking</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        @if (this.User.Identity.IsAuthenticated)
        {
            <div id="navbar" class="container" margin="50%">
                <ul style="list-style-type:none;" class="navbar-expand collapse d-sm-inline-flex flex-sm-row text-lg-center">
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="MiniLigues" asp-action="All">Users Mini Leagues</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Predictions" asp-action="MyPredictions">My Predictions</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="MiniLigues" asp-action="MyMiniLigues">My Mini Leagues</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Rules">Rules</a>
                    </li>
                </ul>
            </div>
        }
    </header>


    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container whiteColor">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>